env:
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:vue/vue3-essential
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - '@typescript-eslint'
  - vue
ignorePatterns:
  - dist
  - dist-electron
rules:
  indent: [error, 2]
  linebreak-style: [error, unix]
  quotes: [error, single]
  semi: [error, always]
  comma-dangle: [error, always-multiline]
  no-multiple-empty-lines: [error, {max: 1}]
  no-multi-spaces: error
  keyword-spacing: error

  '@typescript-eslint/no-var-requires': 0
  '@typescript-eslint/no-explicit-any': [off]
  '@typescript-eslint/ban-ts-comment': [off]
  '@typescript-eslint/no-namespace': off
